---
services:
  neo4j:
    container_name: neo4j-lab4
    image: neo4j:5.12.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
    volumes:
      - ./neo4j/data:/data:rw
      - ./neo4j/logs:/logs:rw
      - ./neo4j/conf:/conf:rw
      - ./neo4j/plugins:/plugins:rw
      - ./neo4j/import:/import:ro
    restart: unless-stopped
